---
title: "Margaux"
author: "Margaux Bailleul"
date: "2023-03-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Chargement des librairies

```{r}
library(ggplot2)
library(leaflet)
library(corrplot)
library(FactoMineR)
library(ade4)
```

Ouverture de la base de données 

```{r}
donnee <- read.csv("Pays_donnees.csv", row.names = 1)
head(donnee)
summary(donnee)
```

Nous allons vérifier s'il y a des données manquantes : 

```{r}
table(is.na(donnee))
```

Il n'y en a pas. 

Nous allons maintenant regarder s'il y a des valeurs aberrantes : 

```{r}

```

Nous allons regarder les types des variables 

```{r}
str(donnee)
```

Aucune valeur aberrante mais nous remarquons des valeurs leviers. 


```{r}
donnees_quanti <- data.frame(scale(donnee))
```


```{r}
var <- donnee[,1:9]
corrplot(cor(var), type = "upper")
```

# ACP

```{r}
acpdonnee <- PCA(donnee)
barplot(acpdonnee$eig[,2])
```
À voir si on met : 

```{r}
s.corcircle(acpdonnee$var, 1, 2, clabel = 0.7)
```


