---
title: "Projet Classification"
author: "Margaux Bailleul"
date: "2023-03-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Chargement des librairies


# 1 - Compréhension et pré-traitement des données

. Donn ́ees manquantes ? Outliers ?
. Standardisation ?
. Choix des variables (regroupement ?) en vue d’une classification

# 2 - Classification des pays en utilisant les différents algorithmes abordés en cours

Utilisation des algorithmes de classification vus en cours
. R ́eflexion sur les choix op ́er ́es
D ́ecider d’une classification finale
. Nombre de groupes ?

# 3 - Comparaison des résultats obtenus avec les différentes méthodes

Caract ́erisation de la partition obtenue
Repr ́esentation informative des r ́esultats
. Graphiques adapt ́es, repr ́esentations factorielles si adapt ́ees
Optionnel : Repr ́esentation spatiale des r ́esultats sur la carte de
Rennes
Faire une ACP

# 4 - Conclusion vis à vis des choix effectués

Quels points peuvent ˆetre critiqu ́es dans vos choix
Quelles pistes pourraient ˆetre explor ́ees pour aller plus loin et/ou
mieux explorer ces donn ́ees ?

# 5 - Suggestion d'une liste de pays à aider en priorité





